pipeline {
    agent any 

    stages {
        stage('Hello World') {
            steps {
                script {
                    echo 'Hello World, Nguyen Van Tu Cuong'
                }
            }
        }
    }
}