export const MAIN_GAMEPLAY_POSTGRESQL = "MAIN_GAMEPLAY_POSTGRESQL"
export const MOCK_GAMEPLAY_POSTGRESQL = "MOCK_GAMEPLAY_POSTGRESQL"
export const MAIN_TELEGRAM_POSTGRESQL = "MAIN_TELEGRAM_POSTGRESQL"
export const MOCK_TELEGRAM_POSTGRESQL = "MOCK_TELEGRAM_POSTGRESQL"