export const HEALTH_CHECK_ENDPOINT = "healthz"
export const HEALTH_CHECK_TIMEOUT = 3000

//injection tokens
export const JOB_REDIS_INJECTION_TOKEN = "JOB_REDIS_INJECTION_TOKEN"
export const ADAPTER_REDIS_INJECTION_TOKEN = "ADAPTER_REDIS_INJECTION_TOKEN"
export const CACHE_REDIS_INJECTION_TOKEN = "CACHE_REDIS_INJECTION_TOKEN"