services:
  server:
    build:
      context: ../..
      dockerfile: apps/cron-scheduler/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production

#docker compose -f apps/cron-scheduler/compose.yaml up -d --build
