services:
  server:
    build:
      context: ../..
      dockerfile: apps/db-helper/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production

#docker compose -f apps/db-helper/compose.yaml up -d