services:
  server:
    build:
      context: ../..
      dockerfile: apps/setup/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production

#docker compose -f apps/setup/compose.yaml up -d