services:
  server:
    build:
      context: ../..
      dockerfile: apps/user-service/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    ports:
      - "3008:3008"

#docker compose -f apps/user-service/compose.yaml up -d --build