//chỉ dùng alias (@) khi mà service khác xài hàng của service này,
// còn nếu mà import bên trong service thì xài relative
//file build nếu import từ alias thì nó sẽ lấy toàn module để nó build
export { AnimalsResolver } from "./animals"
export { AnimalInfosResolver } from "@apps/static-subgraph/src/animal-infos"
export { AnimalInfoThievedByUsersResolver } from "@apps/static-subgraph/src/animal-info-thieved-by-users"
export { BuildingsResolver } from "@apps/static-subgraph/src/buildings"
export { BuildingInfosResolver } from "@apps/static-subgraph/src/building-infos"
export { CropsResolver } from "@apps/static-subgraph/src/crops"
export { DailyRewardPossibilitiesResolver } from "@apps/static-subgraph/src/daily-reward-possibilities"
export { DailyRewardsResolver } from "@apps/static-subgraph/src/daily-rewards"
export { InventoryResolver } from "@apps/static-subgraph/src/inventories"
export { InventoryTypeResolver } from "@apps/static-subgraph/src/inventory-types"
export { PlacedItemTypesResolver } from "@apps/static-subgraph/src/placed-item-types"
export { PlacedItemsResolver } from "@apps/static-subgraph/src/placed-items"
export { ProductResolver } from "@apps/static-subgraph/src/products"
export { SeedGrowthInfosResolver } from "@apps/static-subgraph/src/seed-growth-infos"
export { SeedGrowthInfoThiefedByUsersResolver } from "@apps/static-subgraph/src/seed-growth-info-thiefed-by-users"
export { SpinsResolver } from "@apps/static-subgraph/src/spins"
export { SuppliesResolver } from "@apps/static-subgraph/src/supplies"
export { SystemsResolver } from "@apps/static-subgraph/src/systems"
export { TilesResolver } from "@apps/static-subgraph/src/tiles"
export { ToolsResolver } from "@apps/static-subgraph/src/tools"
export { UpgradeResolver } from "@apps/static-subgraph/src/upgrades"
export { UserResolver } from "@apps/static-subgraph/src/users"
