export const REDIS_KEY = {
    TILES: "TILES",
    ANIMALS: "ANIMALS",
    CROPS: "CROPS",
    TOOLS: "TOOLS",
    BUILDINGS: "BUILDINGS",
    PLACED_ITEMS: "PLACED_ITEMS",
    DAILY_REWARDS: "DAILY_REWARDS",
    SPINS: "SPINS",
    SUPPLIES: "SUPPLIES",
    USERS: "USERS",
}