services:
  server:
    build:
      context: ../..
      dockerfile: apps/static-subgraph/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    ports:
      - "3007:3007"
    networks:
      - graphql-network

networks:
  graphql-network:
    driver: bridge

#docker compose -f apps/static-subgraph/compose.yaml up -d --build