services:
  server:
    build:
      context: ../..
      dockerfile: apps/gameplay-service/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    ports:
      - "3014:3014"

#docker compose -f apps/gameplay-service/compose.yaml up --build -d