services:
  server:
    build:
      context: ../..
      dockerfile: apps/gold-wallet-service/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    ports:
      - "3008:3008"

#docker compose -f apps/gold-wallet-service/compose.yaml up -d --build