services:
  server:
    build:
      context: ../..
      dockerfile: apps/auth-service/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    ports:
      - "3005:3005"

#docker compose -f apps/auth-service/compose.yaml up -d