apiVersion: v1
kind: Pod
metadata:
  name: build-agent
spec:
  containers:
  - name: kaniko
    image: bitnami/kaniko:latest
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    command:
      - /bin/sh
      - -c
      - sleep
      - infinity
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-credentials
        items:
          - key: .dockerconfigjson
            path: config.json