services:
  server:
    build:
      context: ../..
      dockerfile: apps/graphql-gateway/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    ports:
      - "3006:3006"

#docker compose -f apps/graphql-gateway/compose.yaml up -d --build