pipeline {
  agent {
    kubernetes {
      yamlFile 'agent.yaml'
      }
    }

  stages {
    stage('Test Kubernetes') {
      steps {
      container(name: 'kubectl', shell: '/bin/sh') {
        withCredentials([file(credentialsId: 'jenkins-token', variable: 'KUBECONFIG')]) {
          sh "kubectl get pods -n cicd"
          }
        }
      }
    }
  }
}