podTemplate(inheritFrom: 'default')
{
    node(POD_LABEL){
      stage('List Configmaps') {
        withKubeConfig([namespace: "cicd"]) {
          sh 'kubectl get configmap'
        }
  }
    }
}