podTemplate(serviceAccount: 'jenkins-agent', containers: [
  containerTemplate(
    name: 'kubectl',
    image: 'bitnami/kubectl',
    command: '/bin/sh',    // Command to run the shell
    args: '-c "sleep 99d"' // Args for the shell to execute 'sleep 99d'
  )
]) {
  node(POD_LABEL) {
    stage('List Configmaps') {
      // Execute kubectl get pods inside the kubectl container
      container('kubectl') {
        sh 'echo "kubectl"'
        sh 'kubectl get pods -n cicd'
      }
    }
  }
}