services:
  server:
    build:
      context: ../..
      dockerfile: apps/cli/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    volumes:
      - db:/usr/src/app/db
volumes:
    db:

#docker compose -f apps/cli/compose.yaml up --build -d