services:
  server:
    build:
      context: ../..
      dockerfile: apps/cli/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    ports:
      - "3005:3005"

#docker compose -f apps/cli/compose.yaml up --build -d