type UserEntity {
  username: String!
  chainKey: String!
  network: String!
  accountAddress: String!
  inventories: [InventoryEntity!]!
}

type InventoryEntity {
  quantity: String!
  userId: String!
  user: UserEntity!
}

type AnimalEntity {
  yieldTime: Int!
  offspringPrice: Int!
  isNFT: Boolean!
  growthTime: Int!
  availableInShop: Boolean!
  hungerTime: Int!
  minHarvestQuantity: Int!
  maxHarvestQuantity: Int!
  basicHarvestExperiences: Int!
  premiumHarvestExperiences: Int!
  type: AnimalType!
  sickChance: Float!
}

enum AnimalType {
  Poultry
  Livestock
}

type CropEntity {
  growthStageDuration: Int!
  growthStages: Int!
  price: Int!
  premium: Boolean!
  perennial: Boolean!
  nextGrowthStageAfterHarvest: Int!
  minHarvestQuantity: Int!
  maxHarvestQuantity: Int!
  basicHarvestExperiences: Int!
  premiumHarvestExperiences: Int!
  availableInShop: Boolean!
}

type ToolEntity {
  type: ToolType!
  availableIn: AvailableIn!
  index: Int!
}

enum ToolType {
  Scythe
  Steal
  WaterCan
  Herbicide
  Pesticide
}

enum AvailableIn {
  Home
  Neighbor
  Both
}

type UpgradeEntity {
  upgradePrice: Int!
  capacity: Int!
}

type Query {
  animals(args: GetAnimalsArgs!): [AnimalEntity!]!
  crops(args: GetCropsArgs!): [CropEntity!]!
  tools(args: GetToolsArgs!): [ToolEntity!]!
}

input GetAnimalsArgs {
  limit: Int
  offset: Int
}

input GetCropsArgs {
  limit: Int
  offset: Int
}

input GetToolsArgs {
  limit: Int
  offset: Int
}