type UserEntity {
  username: String!
  chainKey: String!
  network: String!
  accountAddress: String!
  golds: Int!
  gems: Float!
  inventories: [InventoryEntity!]!
}

type InventoryEntity {
  quantity: String!
  userId: String!
  user: UserEntity!
}

type AnimalEntity {
  yieldTime: Int!
  offspringPrice: Int!
  isNFT: Boolean!
  growthTime: Int!
  availableInShop: Boolean!
  hungerTime: Int!
  minHarvestQuantity: Int!
  maxHarvestQuantity: Int!
  basicHarvestExperiences: Int!
  premiumHarvestExperiences: Int!
  type: AnimalType!
  sickChance: Float!
}

enum AnimalType {
  Poultry
  Livestock
}

type CropEntity {
  growthStageDuration: Int!
  growthStages: Int!
  price: Int!
  premium: Boolean!
  perennial: Boolean!
  nextGrowthStageAfterHarvest: Int!
  minHarvestQuantity: Int!
  maxHarvestQuantity: Int!
  basicHarvestExperiences: Int!
  premiumHarvestExperiences: Int!
  availableInShop: Boolean!
}

type ToolEntity {
  type: ToolType!
  availableIn: AvailableIn!
  index: Int!
}

enum ToolType {
  Scythe
  Steal
  WaterCan
  Herbicide
  Pesticide
}

enum AvailableIn {
  Home
  Neighbor
  Both
}

type UpgradeEntity {
  upgradePrice: Int!
  capacity: Int!
}

type BuildingEntity {
  buildingKey: BuildingKeyType!
  availableInShop: Boolean!
  type: AnimalType
  maxUpgrade: Int!
  price: Int
  upgrades: [UpgradeEntity!]
}

enum BuildingKeyType {
  Coop
  Pasture
  Home
}

type TileEntity {
  type: TileKeyType!
  price: Float!
  maxOwnership: Int!
  isNFT: Boolean!
  availableInShop: Boolean!
}

enum TileKeyType {
  StarterTile
  BasicTile1
  BasicTile2
  BasicTile3
  FertileTile
}

type SupplyEntity {
  type: SupplyType!
  price: Float!
  availableInShop: Boolean!
  fertilizerEffectTimeReduce: Int
}

enum SupplyType {
  BasicFertilizer
  AnimalFeed
}

type DailyRewardPossibility {
  goldAmount: Int
  tokenAmount: Int
  thresholdMin: Float!
  thresholdMax: Float!
}

type DailyRewardEntity {
  amount: Int
  day: Int!
  isLastDay: Boolean!
  dailyRewardPossibilities: [DailyRewardPossibility!]
}

type SpinEntity {
  type: SpinType!
  goldAmount: Int
  quantity: Int
  tokenAmount: Int
  thresholdMin: Float!
  thresholdMax: Float!
}

enum SpinType {
  Gold
  Seed
  Supply
  Token
}

type Query {
  animals(args: GetAnimalsArgs!): [AnimalEntity!]!
  crops(args: GetCropsArgs!): [CropEntity!]!
  tools(args: GetToolsArgs!): [ToolEntity!]!
  buildings(args: GetBuildingsArgs!): [BuildingEntity!]!
  dailyRewards(args: GetDailyRewardsArgs!): [DailyRewardEntity!]!
  spins(args: GetSpinsArgs!): [SpinEntity!]!
  supplies(args: GetSuppliesArgs!): [SupplyEntity!]!
  tiles(args: GetTilesArgs!): [TileEntity!]!
}

input GetAnimalsArgs {
  limit: Int
  offset: Int
}

input GetCropsArgs {
  limit: Int
  offset: Int
}

input GetToolsArgs {
  limit: Int
  offset: Int
}

input GetBuildingsArgs {
  limit: Int
  offset: Int
}

input GetDailyRewardsArgs {
  limit: Int
  offset: Int
}

input GetSpinsArgs {
  limit: Int
  offset: Int
}

input GetSuppliesArgs {
  limit: Int
  offset: Int
}

input GetTilesArgs {
  limit: Int
  offset: Int
}