services:
  server:
    build:
      context: ../..
      dockerfile: apps/broadcast-service/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    ports:
      - "3004:3004"

#docker compose -f apps/broadcast-service/compose.yaml up --build -d