services:
  server:
    build:
      context: ../..
      dockerfile: apps/seed-data/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production

#docker compose -f apps/seed-data/compose.yaml up -d