services:
  server:
    build:
      context: ../..
      dockerfile: apps/rest-api-gateway/Dockerfile
    env_file:
      - ../../.env.docker
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"

#docker compose -f apps/rest-api-gateway/compose.yaml up --build -d