name: CI/CD Pipeline for Gameplay Subgraph
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: self-hosted
    environment: cifarm
    steps:
    - name: Checkout code
      uses: actions/checkout@v2       
      
    - name: Build Gameplay Subgraph via Docker
      run: |
        docker build -t cifarm/gameplay-subgraph:latest -f apps/gameplay-subgraph/Dockerfile .
        docker push cifarm/gameplay-subgraph:latest

    - name: Upgrade Gameplay Subgraph via Helm
      run: |
          helm upgrade gameplay-subgraph cifarm/service -n containers

