name: CI/CD Pipeline for Gameplay Subgraph

on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: self-hosted
    environment: cifarm
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
      
    - name: Login to Docker Hub
      run: | 
        echo "dckr_pat_Qx20WN7jbnf3s57Y_Hz4isV56Js" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
    - name: Build Gameplay Subgraph via Docker
      run: |
        docker build -t cifarm/gameplay-subgraph:latest -f apps/gameplay-subgraph/Dockerfile .
        docker push cifarm/gameplay-subgraph:latest
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # - name: Set up kubectl for AWS EKS
    #   run: |
    #     aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
    
    # - name: Upgrade Gameplay Subgraph via Helm
    #   run: |
    #     helm upgrade gameplay-subgraph  cifarm/gameplay-subgraph

