name: CI/CD Pipeline for Wallet Service

on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/**'  # Trigger the workflow when files under the 'src' folder change
    #   - 'apps/wallet-service/**'  # Trigger the workflow when files under the 'apps/wallet-service' folder change
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script or build
        run: echo "Changes detected in the apps/wallet-service/"