name: CI/CD Pipeline for Websocket API Gateway

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'  # Trigger the workflow when files under the 'src' folder change
      - 'apps/websocket-node/**'  # Trigger the workflow when files under the 'apps/websocket-node' folder change
jobs:
  deployment:
    concurrency:
      group: "websocket-node-deployment"
      cancel-in-progress: true
    runs-on: self-hosted
    environment: cifarm
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    
    - name: Create manifest.yaml file
      run: |
        if ! helm repo list | grep -q "cifarm"; then
          helm repo add cifarm https://starci-lab.github.io/cifarm-k8s/helm
        else
          helm repo update cifarm
        fi
        helm template websocket-node cifarm/websocket-node > \
          ./manifest.yaml

    - name: Create namespace
      run: kubectl create namespace websocket-node \
           2>/dev/null || echo "Namespace 'websocket-node' already exist"

    - name: Apply Kaniko Build
      run: |
        kubectl delete pod websocket-node-kaniko-build \
        --namespace build \
        2>/dev/null || echo "Pod 'websocket-node-kaniko-build' does not exist"
        kubectl apply -f ./manifest.yaml -l mode=build
  
    - name: Wait for Kaniko Build to Complete
      run: |
        kubectl wait pod/websocket-node-kaniko-build \
        --for jsonpath="status.containerStatuses[0].state.terminated.reason"=Completed \
        --namespace build \
        --timeout=20m
      continue-on-error: false
    - name: Create secret
      run: |
        kubectl delete secret generic websocket-node-env \
        --namespace websocket-node \
        --ignore-not-found
        kubectl create secret generic websocket-node-env --namespace websocket-node \
        --from-literal=WEBSOCKET_API_GATEWAY_PORT=${{ vars.WEBSOCKET_API_GATEWAY_PORT }} \
        --from-literal=GAMEPLAY_POSTGRES_DBNAME=${{ vars.GAMEPLAY_POSTGRES_DBNAME }} \
        --from-literal=GAMEPLAY_POSTGRES_HOST=${{ vars.GAMEPLAY_POSTGRES_HOST }} \
        --from-literal=GAMEPLAY_POSTGRES_PORT=${{ vars.GAMEPLAY_POSTGRES_PORT }} \
        --from-literal=GAMEPLAY_POSTGRES_USER=${{ secrets.GAMEPLAY_POSTGRES_USER }} \
        --from-literal=GAMEPLAY_POSTGRES_PASS=${{ secrets.GAMEPLAY_POSTGRES_PASS }} \
        --from-literal=GAMEPLAY_POSTGRES_SSL=${{ vars.CACHE_REDIS_HOST }} \
        --from-literal=GAMEPLAY_POSTGRES_SSL=${{ vars.CACHE_REDIS_PORT }}
    - name: Apply the Deployment
      run: kubectl apply -f ./manifest.yaml -l mode=deploy